version: 2
jobs:
  build:
    steps:
      - checkout
      - run: npm install
  test:
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
