version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g selenium-side-runner'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
